services:
  - type: web
    name: statement-analyzer-backend
    runtime: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: python -m uvicorn api_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: CORS_ALLOWED_ORIGINS
        value: https://frontendvercel-pied.vercel.app