export const upiApps = [
  'Aditya Birla Capital Digital',
  'Amazon Pay',
  'Bajaj Finserv',
  'BharatPe',
  'ChangeJar',
  'CRED',
  'Curie Money',
  'FamApp by Trio',
  'Fi Money',
  'Flipkart UPI',
  'Freo',
  'Google Pay',
  'Groww',
  'IND Money',
  'Jupiter Money',
  'Kiwi',
  'Kredit.Pe',
  'MobiKwik',
  'Money View',
  'Navi',
  'Niyo Global',
  'One Card',
  'Paytm',
  'Phonepe',
  'POPclub',
  'Rio Money',
  'Samsung Pay',
  'salaryse',
  'Shriram One',
  'super.money',
  'Tata Neu',
  'TimePay',
  'T Wallet',
  'Twid Pay',
  'Ultracash',
  'WhatsApp',
  // You can add more from https://www.npci.org.in/what-we-do/upi/3rd-party-apps
];

export const banks = [
  // Private Sector Banks
  'Axis Bank Ltd.',
  'Bandhan Bank Ltd.',
  'CSB Bank Limited',
  'City Union Bank Ltd.',
  'DCB Bank Ltd.',
  'Dhanlaxmi Bank Ltd.',
  'Federal Bank Ltd.',
  'HDFC Bank Ltd',
  'ICICI Bank Ltd.',
  'IndusInd Bank Ltd',
  'IDFC FIRST Bank Limited',
  'Jammu & Kashmir Bank Ltd.',
  'Karnataka Bank Ltd.',
  'Karur Vysya Bank Ltd.',
  'Kotak Mahindra Bank Ltd',
  'Nainital bank Ltd.',
  'RBL Bank Ltd.',
  'South Indian Bank Ltd.',
  'Tamilnad Mercantile Bank Ltd.',
  'YES Bank Ltd.',
  'IDBI Bank Limited',
  // Local Area Banks
  'Coastal Local Area Bank Ltd',
  'Krishna Bhima Samruddhi LAB Ltd',
  // Small Finance Banks
  'Au Small Finance Bank Ltd.',
  'Capital Small Finance Bank Ltd',
  'Equitas Small Finance Bank Ltd',
  'ESAF Small Finance Bank Ltd.',
  'Suryoday Small Finance Bank Ltd.',
  'Ujjivan Small Finance Bank Ltd.',
  'Utkarsh Small Finance Bank Ltd.',
  'North East Small finance Bank Ltd',
  'Jana Small Finance Bank Ltd',
  'Shivalik Small Finance Bank Ltd',
  'Unity Small Finance Bank Ltd',
  // Payments Banks
  'Airtel Payments Bank Ltd',
  'India Post Payments Bank Ltd',
  'FINO Payments Bank Ltd',
  'Paytm Payments Bank Ltd',
  'Jio Payments Bank Ltd',
  'NSDL Payments Bank Limited',
  // Public Sector Banks
  'Bank of Baroda',
  'Bank of India',
  'Bank of Maharashtra',
  'Canara Bank',
  'Central Bank of India',
  'Indian Bank',
  'Indian Overseas Bank',
  'Punjab & Sind Bank',
  'Punjab National Bank',
  'State Bank of India',
  'UCO Bank',
  'Union Bank of India',
  // Financial Institutions
  'National Bank for Agriculture and Rural Development',
  'Export-Import Bank of India',
  'National Housing Bank',
  'Small Industries Development Bank of India',
  // Regional Rural Banks (RRBs)
  'Assam Gramin Vikash Bank',
  'Andhra Pradesh Grameena Vikas Bank',
  'Andhra Pragathi Grameena Bank',
  'Arunachal Pradesh Rural Bank',
  'Aryavart Bank',
  'Bangiya Gramin Vikash Bank',
  'Baroda Gujarat Gramin Bank',
  'Baroda Rajasthan Kshetriya Gramin Bank',
  'Baroda UP Bank',
  'Chaitanya Godavari GB',
  'Chhattisgarh Rajya Gramin Bank',
  'Dakshin Bihar Gramin Bank',
  'Ellaquai Dehati Bank',
  'Himachal Pradesh Gramin Bank',
  'J&K Grameen Bank',
  'Jharkhand Rajya Gramin Bank',
  'Karnataka Gramin Bank',
  'Karnataka Vikas Gramin Bank',
  'Kerala Gramin Bank',
  'Madhya Pradesh Gramin Bank',
  'Madhyanchal Gramin Bank',
  'Maharashtra Gramin Bank',
  'Manipur Rural Bank',
  'Meghalaya Rural Bank',
  'Mizoram Rural Bank',
  'Nagaland Rural Bank',
  'Odisha Gramya Bank',
  'Paschim Banga Gramin Bank',
  'Prathama U.P. Gramin Bank',
  'Puduvai Bharathiar Grama Bank',
  'Punjab Gramin Bank',
  'Rajasthan Marudhara Gramin Bank',
  'Saptagiri Grameena Bank',
  'Sarva Haryana Gramin Bank',
  'Saurashtra Gramin Bank',
  'Tamil Nadu Grama Bank',
  'Telangana Grameena Bank',
  'Tripura Gramin Bank',
  'Uttar Bihar Gramin Bank',
  'Utkal Grameen Bank',
  'Uttarbanga Kshetriya Gramin Bank',
  'Vidharbha Konkan Gramin Bank',
  'Uttarakhand Gramin Bank',
  // Foreign Banks
  'AB Bank Ltd.',
  'American Express Banking Corporation',
  'Australia and New Zealand Banking Group Ltd.',
  'Barclays Bank Plc.',
  'Bank of America',
  'Bank of Bahrain and Kuwait B.S.C.',
  'Bank of Ceylon',
  'Bank of China Limited',
  'Bank of Nova Scotia',
  'BNP Paribas',
  'Citibank N.A.',
  'Cooperatieve Rabobank U.A./ Coöperatieve Centrale Raiffeisen-Boerenleenbank B.A.',
  'Credit Agricole Corporate and Investment Bank',
  'CTBC Bank Co., Ltd.',
  'DBS Bank India Limited',
  'Deutsche Bank A.G.',
  'Doha Bank Q.P.S.C',
  'Emirates NBD Bank P.J.S.C',
  'First Abu Dhabi Bank PJSC',
  'FirstRand Bank Limited',
  'Hong Kong and Shanghai Banking Corporation Limited',
  'Industrial and Commercial Bank of China',
  'Industrial Bank of Korea',
  'J.P. Morgan Chase Bank N.A.',
  'JSC VTB Bank',
  'KEB Hana Bank',
  'Kookmin Bank',
  'Mashreq bank P.S.C',
  'Mizuho Bank Ltd.',
  'MUFG Bank, Ltd.',
  'Nong Hyup Bank',
  'NatWest Markets Plc',
  'PT Bank Maybank Indonesia TBK',
  'Qatar National Bank (Q.P.S.C.)',
  'Sberbank',
  'SBM Bank (India) Limited',
  'Shinhan Bank',
  'Societe Generale',
  'Sonali Bank Ltd.%',
  'Standard Chartered Bank',
  'Sumitomo Mitsui Banking Corporation',
  'UBS AG',
  'United Overseas Bank Limited',
  'Woori Bank',
]; 